/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package web.parqueadero.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 02-03-2019
 * 
 * XDoclet definition:
 * @struts.form name="precioFormBean"
 */
public class PrecioFormBean extends ActionForm {
	/*
	 * Generated fields
	 */

	/** tipoVehiculo property */
	private String tipoVehiculo;

	/** precio property */
	private String precio;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the tipoVehiculo.
	 * @return String
	 */
	public String getTipoVehiculo() {
		return tipoVehiculo;
	}

	/** 
	 * Set the tipoVehiculo.
	 * @param tipoVehiculo The tipoVehiculo to set
	 */
	public void setTipoVehiculo(String tipoVehiculo) {
		this.tipoVehiculo = tipoVehiculo;
	}

	/** 
	 * Returns the precio.
	 * @return String
	 */
	public String getPrecio() {
		return precio;
	}

	/** 
	 * Set the precio.
	 * @param precio The precio to set
	 */
	public void setPrecio(String precio) {
		this.precio = precio;
	}
}