/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package web.parqueadero.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

/** 
 * MyEclipse Struts
 * Creation date: 02-01-2019
 * 
 * XDoclet definition:
 * @struts.form name="usuarioFormBean"
 */
public class UsuarioFormBean extends ActionForm {
	/*
	 * Generated fields
	 */

	/** nombre property */
	private String nombre;

	/** tipoUsuario property */
	private String tipoUsuario;

	/** nombreParqueadero property */
	private String nombreParqueadero;

	/** contrasena property */
	private String contrasena;

	/** correo property */
	private String correo;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		
		ActionErrors errores = new ActionErrors();
		if(this.nombre.equals("") || this.nombre == null){
			errores.add("errorNombre", new ActionMessage("error.nombre"));
		}
		if(this.correo.equals("") || this.correo == null){
			errores.add("errorCorreo", new ActionMessage("error.correo"));
		}else if(!(this.correo.contains("@"))){
			errores.add("errorCorreo", new ActionMessage("error.correo2"));
		}
		if(this.nombreParqueadero.equals("") || this.nombreParqueadero == null){
			errores.add("errorNombreParqueadero", new ActionMessage("error.parqueadero"));
		}
		if(this.contrasena.equals("") || this.contrasena == null){
			errores.add("errorContrasena", new ActionMessage("error.contrasena"));
		}
		return errores;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the nombre.
	 * @return String
	 */
	public String getNombre() {
		return nombre;
	}

	/** 
	 * Set the nombre.
	 * @param nombre The nombre to set
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/** 
	 * Returns the tipoUsuario.
	 * @return String
	 */
	public String getTipoUsuario() {
		return tipoUsuario;
	}

	/** 
	 * Set the tipoUsuario.
	 * @param tipoUsuario The tipoUsuario to set
	 */
	public void setTipoUsuario(String tipoUsuario) {
		this.tipoUsuario = tipoUsuario;
	}

	/** 
	 * Returns the nombreParqueadero.
	 * @return String
	 */
	public String getNombreParqueadero() {
		return nombreParqueadero;
	}

	/** 
	 * Set the nombreParqueadero.
	 * @param nombreParqueadero The nombreParqueadero to set
	 */
	public void setNombreParqueadero(String nombreParqueadero) {
		this.nombreParqueadero = nombreParqueadero;
	}

	/** 
	 * Returns the contrasena.
	 * @return String
	 */
	public String getContrasena() {
		return contrasena;
	}

	/** 
	 * Set the contrasena.
	 * @param contrasena The contrasena to set
	 */
	public void setContrasena(String contrasena) {
		this.contrasena = contrasena;
	}

	/** 
	 * Returns the correo.
	 * @return String
	 */
	public String getCorreo() {
		return correo;
	}

	/** 
	 * Set the correo.
	 * @param correo The correo to set
	 */
	public void setCorreo(String correo) {
		this.correo = correo;
	}
}