/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package web.parqueadero.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 02-01-2019
 * 
 * XDoclet definition:
 * @struts.form name="usuarioIngresaFormBean"
 */
public class UsuarioIngresaFormBean extends ActionForm {
	/*
	 * Generated fields
	 */

	/** nombre property */
	private String nombre;

	/** tipoUsuario property */
	private String tipoUsuario;

	/** contrasena property */
	private String contrasena;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the nombre.
	 * @return String
	 */
	public String getNombre() {
		return nombre;
	}

	/** 
	 * Set the nombre.
	 * @param nombre The nombre to set
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/** 
	 * Returns the tipoUsuario.
	 * @return String
	 */
	public String getTipoUsuario() {
		return tipoUsuario;
	}

	/** 
	 * Set the tipoUsuario.
	 * @param tipoUsuario The tipoUsuario to set
	 */
	public void setTipoUsuario(String tipoUsuario) {
		this.tipoUsuario = tipoUsuario;
	}

	/** 
	 * Returns the contrasena.
	 * @return String
	 */
	public String getContrasena() {
		return contrasena;
	}

	/** 
	 * Set the contrasena.
	 * @param contrasena The contrasena to set
	 */
	public void setContrasena(String contrasena) {
		this.contrasena = contrasena;
	}
}