/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package web.parqueadero.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 02-02-2019
 * 
 * XDoclet definition:
 * @struts.form name="vehiculoFormBean"
 */
public class VehiculoFormBean extends ActionForm {
	/*
	 * Generated fields
	 */

	/** responsable property */
	private String responsable;

	/** id property */
	private String id;

	/** tiempo property */
	private String tiempo;

	/** horaEntrada property */
	private String horaEntrada;

	/** horaSalida property */
	private String horaSalida;

	/** valorPagar property */
	private String valorPagar;

	/** placa property */
	private String placa;
	
	private String tipoVehiculo;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the responsable.
	 * @return String
	 */
	public String getResponsable() {
		return responsable;
	}

	/** 
	 * Set the responsable.
	 * @param responsable The responsable to set
	 */
	public void setResponsable(String responsable) {
		this.responsable = responsable;
	}

	/** 
	 * Returns the id.
	 * @return String
	 */
	public String getId() {
		return id;
	}

	/** 
	 * Set the id.
	 * @param id The id to set
	 */
	public void setId(String id) {
		this.id = id;
	}

	/** 
	 * Returns the tiempo.
	 * @return String
	 */
	public String getTiempo() {
		return tiempo;
	}

	/** 
	 * Set the tiempo.
	 * @param tiempo The tiempo to set
	 */
	public void setTiempo(String tiempo) {
		this.tiempo = tiempo;
	}

	/** 
	 * Returns the horaEntrada.
	 * @return String
	 */
	public String getHoraEntrada() {
		return horaEntrada;
	}

	/** 
	 * Set the horaEntrada.
	 * @param horaEntrada The horaEntrada to set
	 */
	public void setHoraEntrada(String horaEntrada) {
		this.horaEntrada = horaEntrada;
	}

	/** 
	 * Returns the horaSalida.
	 * @return String
	 */
	public String getHoraSalida() {
		return horaSalida;
	}

	/** 
	 * Set the horaSalida.
	 * @param horaSalida The horaSalida to set
	 */
	public void setHoraSalida(String horaSalida) {
		this.horaSalida = horaSalida;
	}

	/** 
	 * Returns the valorPagar.
	 * @return String
	 */
	public String getValorPagar() {
		return valorPagar;
	}

	/** 
	 * Set the valorPagar.
	 * @param valorPagar The valorPagar to set
	 */
	public void setValorPagar(String valorPagar) {
		this.valorPagar = valorPagar;
	}

	/** 
	 * Returns the placa.
	 * @return String
	 */
	public String getPlaca() {
		return placa;
	}

	/** 
	 * Set the placa.
	 * @param placa The placa to set
	 */
	public void setPlaca(String placa) {
		this.placa = placa;
	}
	
	public String getTipoVehiculo(){
		return this.tipoVehiculo;
	}
	public void setTipoVehiculo(String tipoVehiculo){
		this.tipoVehiculo = tipoVehiculo;
	}
}