/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package web.parqueadero.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import java.util.List;
import java.util.ArrayList;
import modelo.Vehiculo;



/** 
 * MyEclipse Struts
 * Creation date: 02-02-2019
 * 
 * XDoclet definition:
 * @struts.action
 */
public class DesplegarParqueoAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
                int idRecup = Integer.parseInt(request.getParameter("idRecuperar"));
                System.out.println("********" + idRecup);
                Vehiculo parqueoRecup = new Vehiculo();
                List<Vehiculo> parqueos = (List<Vehiculo>) request.getSession().getAttribute("parqueos");
                for(Vehiculo v : parqueos){
                    if(v.getId() == idRecup){
                        parqueoRecup.setId(v.getId());
                        parqueoRecup.setTipoVehiculo(v.getTipoVehiculo());
                        parqueoRecup.setPlaca(v.getPlaca());
                        parqueoRecup.setHoraEntrada(v.getHoraEntrada());
                    }
                }
                request.setAttribute("parqueoRecup", parqueoRecup);
		return mapping.findForward("desplegado");
	}
}