/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package web.parqueadero.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import web.parqueadero.struts.form.UsuarioFormBean;
import web.parqueadero.struts.form.UsuarioIngresaFormBean;

import javax.servlet.http.HttpSession;
import modelo.Usuario;
import service.parqueadero.ParkingServicios;
import service.parqueadero.ParkingServiciosImpl;
/** 
 * MyEclipse Struts
 * Creation date: 02-01-2019
 * 
 * XDoclet definition:
 * @struts.action path="/ingresaUsuario" name="usuarioFormBean" scope="request"
 */
public class IngresaUsuarioAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UsuarioIngresaFormBean usuarioForm = (UsuarioIngresaFormBean) form;
                
                Usuario user = new Usuario();
                user.setNombre(usuarioForm.getNombre());
                user.setContrasena(usuarioForm.getContrasena());
                user.setTipoUsuario(usuarioForm.getTipoUsuario());
                /*
                user.setNombreParqueadero("");
                user.setCorreo("");
                user.setIdUsuario(0);
                */
                /*
		String nombre = usuarioForm.getNombre();
		String contrasena = usuarioForm.getContrasena();
		String tipoUsuario = usuarioForm.getTipoUsuario();
                */
		
		//cuando tenga la base ade datos aca se recuperarn todos los usuario
                ParkingServicios servicios = new ParkingServiciosImpl();
                Usuario usuarioRecibido = servicios.verificarUsuario(user);
		/*
		HttpSession sesion = request.getSession();
		Usuario u = (Usuario) sesion.getAttribute("usuarioIngresado");
		
		System.out.println("****" + u.getNombre()+" - " + nombre);
		System.out.println("****" + u.getContrasena()+" - " + contrasena);
		System.out.println("****" + u.getTipoUsuario()+" - " + tipoUsuario);
		
		if(nombre.equals(u.getNombre()) && contrasena.equals(u.getContrasena()) && tipoUsuario.equals(u.getTipoUsuario())){
			return mapping.findForward("valido");
		}else{
			request.setAttribute("mensaje", "El nombre/contrase�a es incorrecto");
			return mapping.findForward("invalido");
		}
                */
                if(usuarioRecibido == null){
                    request.setAttribute("mensaje", "El nombre/contrasena es incorrecto");
                    return mapping.findForward("invalido");
                }else{
                    HttpSession sesion = request.getSession();
                    sesion.setAttribute("usuarioIngresado", usuarioRecibido);
                    return mapping.findForward("valido");
                }
	}
}