/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package web.parqueadero.struts.action;

import java.sql.SQLException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import web.parqueadero.struts.form.UsuarioFormBean;

import modelo.Usuario;

import data.parqueadero.usuarios.jdbc.UsuarioDaoJDBC;
import data.parqueadero.usuarios.jdbc.UsuarioDao;
import data.parqueadero.usuarios.dto.UsuarioDTO;
import data.parqueadero.usuarios.jdbc.Conexion;

import service.parqueadero.ParkingServicios;
import service.parqueadero.ParkingServiciosImpl;
/** 
 * MyEclipse Struts
 * Creation date: 02-01-2019
 * 
 * XDoclet definition:
 * @struts.action path="/registraUsuario" name="usuarioFormBean" scope="request"
 */
public class RegistraUsuarioAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UsuarioFormBean usuarioForm = (UsuarioFormBean) form;
		
		String nombre = usuarioForm.getNombre();
		String correo = usuarioForm.getCorreo();
		String nombreParqueadero = usuarioForm.getNombreParqueadero();
		String contrasena = usuarioForm.getContrasena();
		String tipoUsuario = usuarioForm.getTipoUsuario();
		
		Usuario usuarioRegistrar = new Usuario(nombre,correo,nombreParqueadero,contrasena,tipoUsuario);
		
                ParkingServicios servicios = new ParkingServiciosImpl();
                servicios.registrarUsuario(usuarioRegistrar);
                /*
		HttpSession sesion = request.getSession();
		sesion.setAttribute("usuarioIngresado", usuarioRegistrado);
		request.setAttribute("mensaje", "Usuario Registrado Exitosamente");
		*/
		//System.out.println(nombre + correo + nombreParqueadero + contrasena + tipoUsuario);
		
		//PRUEBA DE LA BASE DE DATOS
                /*
		UsuarioDTO u = new UsuarioDTO();
		u.setNombre(nombre);
		u.setCorreo(correo);
		u.setNombreParqueadero(nombreParqueadero);
		u.setContrasena(contrasena);
		u.setTipoUsuario(tipoUsuario);
		
		UsuarioDao usuarioDao;
		try {
			usuarioDao = new UsuarioDaoJDBC(Conexion.getConnection());
			usuarioDao.insert(u);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		*/
		
		//System.out.println(nombre + correo + nombreParqueadero + contrasena + tipoUsuario);
                request.setAttribute("mensaje", "Usuario Registrado Exitosamente");
		return mapping.findForward("registrado");
	}
}