/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package web.parqueadero.struts.action;

import java.sql.SQLException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import web.parqueadero.struts.form.PrecioFormBean;

import java.util.List;
import java.util.ArrayList;
import modelo.Precio;
import modelo.Usuario;

import service.parqueadero.ParkingServicios;
import service.parqueadero.ParkingServiciosImpl;
/** 
 * MyEclipse Struts
 * Creation date: 02-03-2019
 * 
 * XDoclet definition:
 * @struts.action path="/seleccionPrecios" name="precioFormBean" scope="request"
 */
public class SeleccionPreciosAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		PrecioFormBean precioForm = (PrecioFormBean) form;
		
                try{
                    double valorVerificar = Double.parseDouble(precioForm.getPrecio());
                }catch(Exception e){
                    e.printStackTrace();
                    request.setAttribute("mensaje", "Por favor ingrese un precio valido");
                    return mapping.findForward("precioinvalido");
                }
                
		String tipoVehiculo = precioForm.getTipoVehiculo();
		double precio = Double.parseDouble(precioForm.getPrecio());
                String idPrecio = Integer.toString(((Usuario) request.getSession()
                                .getAttribute("usuarioIngresado")).getIdUsuario()) + tipoVehiculo.substring(0, 3);
		
		//Precio precio1 = new Precio(tipoVehiculo, precio);
                
                Precio precio1 = new Precio(idPrecio,tipoVehiculo,precio);
                boolean bandera = false;

                    ParkingServicios servicios = new ParkingServiciosImpl();
                    //bandera = servicios.registrarPrecios(precio1);
                    
                    int id =((Usuario)request.getSession().getAttribute("usuarioIngresado")).getIdUsuario();
                    servicios.recuperarPreciosPorId(id);
 
                    for(Precio p : servicios.recuperarPreciosPorId(id)){
                        //System.out.println("****" + precio.getPrecio()+ "++++" );

                        if(p.getTipoVehiculo().equals(tipoVehiculo)){
                                
                            //crear servicio para actualizar
                            bandera = servicios.modificarPrecios(precio1);
                            
                        }
                        
                        
                    }                    
                    if(!bandera){
                       bandera = servicios.registrarPrecios(precio1);                        
                    }
                    
                    if(bandera){
                        HttpSession sesion = request.getSession();
                        sesion.setAttribute(tipoVehiculo, precio1);  
                    }
                    
                                      
                   
                
		
                
		
                
		return mapping.findForward("actualizarPrecio");
	}
}